### ISSUE TITLE
Scheduled reboot does not work

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rise-player#18]
Steps to reproduce:
1. Have a display correctly configured and running the (new) native player.
2. Schedule a reboot at a specific time.

Result:
Nothing happens at or around the time specified for the reboot

How it should work:
Computer that the player is running should reboot at the configured time.

Link to Displays (in uptime):
win7: http://rvauser.appspot.com/#/DISPLAY_MANAGE/id=CWJHKWKAK6ZM?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55
linux: http://rvauser.appspot.com/#/DISPLAY_MANAGE/id=NCVP8RP6HV8P?cid=fee1f642-cdd1-4bc4-8f93-1fc97cb00d55

OS:
Ubuntu 14.04 & Windows 7

Chrome Ver:
Chrome 44.0.2403.157 (bundled version)

RP Version:
Linux: RisePlayer 2015.09.22.12.50
Windows: RisePlayer 2015.09.16.17.00

Additional Notes:
Clicking the reboot button works fine, but scheduling the reboot does not.

**Comment by tejohnso** [comment]
@mfisher11 I wasn't able to duplicate this on a fresh install.  Can you confirm?

**Comment by mfisher11** [comment]
@tejohnso There have been quite a few updates since this ticket was created (9/24).  If you are not able to replicate the problem then it was likely fixed in a later revision.  Does someone in CS want to see if this is still a problem, @robb-price ?  Thanks!

**Comment by lapinnoir** [comment]
@mfisher11 I haven't been able to recreate this issue when I did restarts on win 7, 8.1, 10 and linux 14.04, 15.10 the new Installer yesterday evening.  fyi @robb-price

**Comment by robb-price** [comment]
@lapinnoir Thanks!

@mfisher11 Since we can't recreate, we'll just close it, but let us know if you see this pop up again.

Thanks!
