### ISSUE TITLE
Items can be swiped off screen.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player#32]
**How to recreate**
1. Schedule a presentation with any content on a display with touch.
2. Swipe your finger across the display.

**What happens**
The content will swipe across and off the screen.

**What should happen**
Content should not be able to be swiped off the screen.

**Video**
http://www.screencast.com/t/r3oBmGF2VsCi

**Media Player Details**
OS: Windows 7 x64
Player Version: RisePlayer 2016.02.11.21.00
Installed browser: Chrome 47.0.2526.106

**Comment by fjvallarino** [comment]
@btfrise Does this happen only on Windows?

**Comment by ahmedalsudani** [comment]
Thanks @btfrise. I believe this was fixed by https://github.com/Rise-Vision/rise-player/pull/30. We might need to create a new Player release.

**Comment by tejohnso** [comment]
@ahmedalsudani It looks like you didn't merge that fix to master so it didn't make it into the build.

**Comment by ByronDarlison** [comment]
@tejohnso @fjvallarino @ahmedalsudani is the plan to ship this next week now?

**Comment by btfrise** [comment]
@fjvallarino no, linux as well.

**Comment by ahmedalsudani** [comment]
@tejohnso you are correct. I just submitted a PR for that.

@ByronDarlison I think we can ship this come Monday, once this release cycle is complete.

**Comment by ByronDarlison** [comment]
@ahmedalsudani @tejohnso to confirm, will this go out with the Tuesday release to CS? Is that what you mean by Monday? Thanks

**Comment by ahmedalsudani** [comment]
@ByronDarlison I'm talking about something else here. We have a cache rollout happening right now, and we plan on raising the percentage to 100% tomorrow. Once that's done, we can start a new rollout that includes the new release of the player.

This will be separate from the installer release, which we plan to hand to CS on Tuesday. I can clarify the difference for you over a call if you'd like.

/cc @tejohnso

**Comment by ByronDarlison** [comment]
@ahmedalsudani I understand the difference, what I am asking about is when are we handing to CS to test? You're not suggesting we skip testing and go straight to production are you?

**Comment by ahmedalsudani** [comment]
@ByronDarlison Strange. If I recall correctly, CS was sent a build and marked it as fixed. I can't find the card though. I'll get back to you on this.

**Comment by ahmedalsudani** [comment]
@ByronDarlison my mistake. This was apparently never tested by CS. 

The fix has passed my testing though. I'll send out a build to CS early tomorrow so we can hopefully send it out early next week.

**Comment by ByronDarlison** [comment]
@ahmedalsudani I am not following. We are sending builds to CS every Tuesday for them to test and release the following Monday. What do you mean you are sending a build to CS early tomorrow so that we can send it out next week?

**Comment by ahmedalsudani** [comment]
@ByronDarlison you are correct, but those are installer builds. I'm talking about a player build, which has a separate testing procedure. I can hold off on sending the build to CS until Tuesday if you'd like

**Comment by ByronDarlison** [comment]
@ahmedalsudani what separate testing procedure do we have? As far as I know if we change anything to do with Player we put the Player through a whole series of tests, and that work is very expensive. We don't do it for each issue we discover, we queue the fixes for the issues and do it once per week. Unless you know something I don't this work should be queued for the next release to CS and it should not be treated as a release onto itself. Thanks

**Comment by ahmedalsudani** [comment]
Ok, @ByronDarlison. I'll send the build on Tuesday as part of the release

**Comment by tejohnso** [comment]
@btfrise This is corrected now?

**Comment by btfrise** [comment]
This is fixed.
