### ISSUE TITLE
Restart player does not have any effect.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player#34]
**How to recreate**
1. Install newest Rise Player installer on any media player.
2. Assign a display ID.
3. On either displays.risevision.com, or http://rva.risevision.com/#/DISPLAYS, select the display that you just set up.
4. Select restart player

**What happens**
The player is not affected in any way.

**What should happen**
The player should restart and refresh all content.

**Notes**
Windows 7 x32 & x64 / Windows 10 x64 / Ubuntu 14.04 x64
Latest installer from https://help.risevision.com/user/create-a-display

**Comment by btfrise** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;bUZPdtw1&#x2F;1493-test-reboot-restart-player-on-new-installer"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Test reboot&#x2F;restart player on new installer.</a>

**Comment by tejohnso** [comment]
@btfrise This is ok to close?

**Comment by btfrise** [comment]
This is fixed.
