### ISSUE TITLE
Items can be swiped off screen - 2016.3.1 Installer.

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-player#38]
How to recreate
1. Schedule a presentation with any content on a display with touch.
2. Swipe your finger across the display.

What happens
The content will swipe across and off the screen.

What should happen
Content should not be able to be swiped off the screen.

Video
https://drive.google.com/file/d/0B209NVr7akhlVlRKVjBIOXQ5QzQ/view?usp=sharing

Media Player Details
OS: Windows 7 x32/x64
Player Version: RisePlayer 2016.02.11.21.00
Installed browser: Chrome 48.0.2564.116

**Comment by tejohnso** [comment]
@btfrise Can you try again with the most recent player installed?

**Comment by btfrise** [comment]
Fixed with Rise Player 2016.02.24.13.00
