### ISSUE TITLE
Weather Widget error causes Viewer stall

### ISSUE THREAD

**Issue by RV-Adrian** [Rise-Vision/rise-player#52]
When Rise Player tries to load a Presentation containing an error in the Weather Widget, Viewer continually shows the circular 'loading..' spinner, and not the error messages you would see in Editor's Save/Preview.
https://store.risevision.com/product/54/weather-forecast-and-conditions

This goes for both 'Agree to Terms' widget errors, and not having a proper Custom Address to pull weather data from.

**Comment by tejohnso** [comment]
@alanclayton Is this a known issue?

**Comment by alanclayton** [comment]
@tejohnso Not that I'm aware of. @robb-price can someone in CS investigate?

**Comment by RV-Adrian** [comment]
@robb-price 
This was the case me on Win10-64 bit, using a NUC. Thx!

**Comment by robb-price** [comment]
@RV-Adrian Is this when you opened the Settings? When you previewed the Widget? I can see everything fine in this Presentation: https://apps.risevision.com/editor/workspace/9ef4b8f6-1a73-4d3a-a31e-d0eedf488e81/?cid=f114ad26-949d-44b4-87e9-8528afc76ce4 on a Windows 10 and Linux box, as well as in preview.

Let me know if there is anything further that needs to be investigated.

Thanks!

**Comment by RV-Adrian** [comment]
@robb-price
 I was testing out the onboarding flow and randomly dropped in a Weather widget without 'agreeing' or adding a location:
![image](https://cloud.githubusercontent.com/assets/11826611/15837151/fb119d00-2c05-11e6-890a-9314d5deb8c6.png)

Save+Preview shows the 'agree' error (or just a blank widget with Celsius and nothing else if no location added), but trying to get that same Presentation to load in Rise Player resulted in an endless spinner.
Ideally, the user can see the same error/issue through Rise Player, and then get an idea of where the problem lies.

**Comment by robb-price** [comment]
@RV-Adrian I'm not able to create the same behaviour. Let's have a quick discussion tomorrow to determine if we are missing each other and if we have a bug.

Thanks!

**Comment by ByronDarlison** [comment]
@robb-price @alanclayton any conclusions as to whether this is a viewer or weather widget issue? Thanks

**Comment by RV-Adrian** [comment]
@robb-price Ok, sounds good. I'll see if I can recreate in the meantime on the media player here.

**Comment by robb-price** [comment]
@ByronDarlison I think it is  weather Widget issue, but I cannot recreate the same behaviour @RV-Adrian is seeing. We are going to discuss tomorrow to determine and will assign appropriately.

**Comment by ByronDarlison** [comment]
@rodrigopavezi okay. I am moving the card to your board and will leave it with you to determine where it should fall. Thanks

**Comment by RV-Adrian** [comment]
@robb-price I was able to recreate the issue with a new account. Let's walk through the steps tomorrow. Thx!

**Comment by RV-Adrian** [comment]
Steps to recreate:
_- Note this needs to be with a brand new Google account, not one that has been registered with RV previously. Deleting the Company and logging back in won't work._
- Register with new test Google account
- Complete sign in process, land on CTA Launcher Page
- Select 'Add Presentation'
- Select 'Full Screen Image' template
- Select 'Start With This Template'
- Name your Presentation anything. Apply.
- Add Placeholder
- Add Widget
- Select 'Digichief Weather'
- Hit 'Save Changes' immediately on the settings screen. No settings entered. Apply.
- Hit 'Save and Preview', you should see a red error requesting Terms agreement. Close Preview tab and return to Editor.
- You should see a 'Congrats' popup. Select 'Add Display'.
- Enter a name, and Save.
- Use this Display ID with Rise Player. The presentation/schedule that's been auto-created never shows. (The Display does become Active, however)

This may extend to any new Presentation within this flow, didn't dig much deeper. Thx!

**Comment by robb-price** [comment]
This is not unique to the Weather Widget, I have recreated with other Widgets. Closing this bug and opening another that outlines the entire issue.
