### ISSUE TITLE
Displays not updating with Player Professional status even when licensed

### ISSUE THREAD

**Issue by raydurkin** [Rise-Vision/rise-player#57]
Kent State University purchased 50 licenses for Rise Player Professional

On their account page here: https://store.risevision.com/account?cid=0ece0135-7499-47a6-8142-db9e07cc71b5 you can see that they have selected all the displays in this company.

On their displays page here: https://apps.risevision.com/displays/list?cid=0ece0135-7499-47a6-8142-db9e07cc71b5 you can see that not all displays have updated to professional status.

Have rebooted each of of the media players with no change.

**Comment by raydurkin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(1) Issue 57: Rise Player Professional not updating on Displays even though display is selected in account page](https://trello.com/c/yOIp4Wlw/5505-1-issue-57-rise-player-professional-not-updating-on-displays-even-though-display-is-selected-in-account-page)

**Comment by robb-price** [comment]
Displays now all show as Professional. Closing this.
