### ISSUE TITLE
(LNX32) Flash crashes showing a message reporting it, and a warning about unsupported/deprecation

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rise-player#7]
Steps to reproduce:
1. Run the native player that contains a presentation with flash content

Result:
A visible message about flash crashing, and that it will be unsupported soon.
(see screenshot)

How it should work:
Content should play without any warnings/crashes.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=a73fec33-6e96-4bc0-80ef-9bd6d0ccb478?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Linux  (Ubuntu 14.04 32 bit)

Chrome Ver:
Bundled version for native player

![screenshot from 2015-08-31 15 55 41](https://cloud.githubusercontent.com/assets/10407181/9592401/2e79e420-5008-11e5-8b03-550e5d407ddc.png)

**Comment by ByronDarlison** [comment]
@mfisher11 @tejohnso @fjvallarino @alanclayton @btfrise I thought we had deprecated Flash and weren't supporting any further development? Thanks

**Comment by btfrise** [comment]
@fjvallarino this is confirmed fixed.
