### ISSUE TITLE
(LNX32) Touch interaction does not work properly

### ISSUE THREAD

**Issue by mfisher11** [Rise-Vision/rise-player#8]
Steps to reproduce:
1. Assign the presentation listed below (this supports touch, dragging and multitouch)
2. Switch to "circles" (or try to switch to circles by touching the appropriate button)

Multiple issues/results:
Touching the screen sometimes works.
Placement/detection is sometimes incorrect or ignored.
A "right click" is sometimes detected/interpreted.
Dragging does not work as expected (usually not at all).
Multi-touch and drag (rotating/enlarging the images in that presentation) does not work.

How it should work:
Touch responses should be predictable (location-wise) and should not be treated as a right-click.
Dragging should work.
Multi-touch and dragging should work.

Link to Presentation:
http://rvauser.appspot.com/#/PRESENTATION_MANAGE/id=4ecee3a1-97c0-4963-acb2-6b9ca704a1b8?cid=e514fd51-fadd-4e19-94af-f92549772c7f

OS:
Linux (Ubuntu 14.04 32 bit)

Chrome Ver:
Bundled version

**Comment by btfrise** [comment]
This is solved with the latest .jar file provided by @fjvallarino.
